# -*- coding: utf-8 -*-
"""diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vm67WpR2hN-RSLnwhKjkbsskDhlayHrO
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

di=pd.read_excel('/content/diabetes.xlsx')

di.head()

di.isnull().sum()

logic=LogisticRegression()

aa=di[['preg','plas','pres','skin','insu','mass','pedi','age']]

bb=di['class']

logic.fit(aa,bb)

preg=int(input("enter the preg"))
plas=int(input("enter the plas"))
pres=int(input("enter the pres"))
skin=int(input("enter the skin"))
insu=int(input("enter the insu"))
mass=float(input("enter the mass"))
pedi=float(input("enter the pedi"))
age=int(input("enter the age"))
ans=logic.predict([[preg,plas,pres,skin,insu,mass,pedi,age]])
print(ans)

logic.score(aa,bb)