# -*- coding: utf-8 -*-
"""flighttk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tv56ma0Vp9PnAFhqH9FGNvdZpVWnM2ef
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

tk=pd.read_csv('/content/Clean_Dataset.csv')

tk.isnull().sum()

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

tk["source2"]=le.fit_transform(tk["source_city"])

tk["source3"]=le.fit_transform(tk["destination_city"])

tk["airline1"]=le.fit_transform(tk["airline"])

tk["class"]=le.fit_transform(tk["class"])

tk=tk.sample(frac=1)

tk.head()

aa=tk[['duration','source2','source3','airline1','class']]

bb=tk['price']

lr=LinearRegression()

lr.fit(aa,bb)

lr.predict([[2,4,0,3,1]])