# -*- coding: utf-8 -*-
"""graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqI3nW1S5RYc_eRYNYXJKMcRHOotB7UU
"""

import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset('tips')

sns.scatterplot(x='total_bill', y='tip', data=tips)
plt.title('Scatterplot')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

sns.barplot(x='total_bill', y='tip', data=tips)
plt.title('Barplot')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

sns.boxplot(x='total_bill', y='tip', data=tips)
plt.title('Boxplot')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

sns.violinplot(x='total_bill', y='tip', data=tips)
plt.title('Viollinplot')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

iris=sns.load_dataset('iris')
correlation_matrix = iris.select_dtype(include='number').corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

iris = sns.load_dataset('iris')

sns.pairplot(iris)
plt.title('Pairplot')
plt.show()

tips=sns.load_dataset('tips')
sns.jointplot(x='total_bill', y='tip', data=tips, kind="hex")
plt.title('Jointplot')
plt.xlabel('Total Bill($)')
plt.ylabel('Tip($)')
plt.show()

titanic=sns.load_dataset('titanic')
sns.countplot(x='class', data=titanic)
plt.title('Passenger Class Distribution')
plt.xlabel('Class')
plt.ylabel('Count')
plt.show()