# -*- coding: utf-8 -*-
"""Reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBqucpb15_CI5gVGBPR4xOi3oPLo65WT
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

review=pd.read_csv('/content/product_reviews_clean.csv')

vectorizer=TfidfVectorizer(stop_words='english')
x=vectorizer.fit_transform(review['review'])
y=review['sentiment']

lr=LogisticRegression()
lr.fit(x,y)

new_review=input("Enter the product review:")
new_vec=vectorizer.transform([new_review])
prediction=lr.predict(new_vec)

print("sentiment:","Positive" if prediction[0]==1 else "Negative")