# -*- coding: utf-8 -*-
"""Salary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wpc3xNZcYoW22MUJwsAeIQhq8FOvlToe
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

salf=pd.read_csv('/content/Salary Data.csv')

salf.head()

salf.isnull().sum()

salf.dropna(inplace=True)

salf.isnull().sum()

lr=LinearRegression()

a=salf[['Age','Gender','Education Level','Years of Experience']]

b=salf['Salary']

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

salf["edu1"]=le.fit_transform(salf["Education Level"])

salf.tail()

salf["gen1"]=le.fit_transform(salf["Gender"])

salf.tail()

info=salf[['Age','gen1','edu1','Years of Experience']]

a=salf['Salary']

lr.fit(info,a)

lr.predict([[25,1,1,1]])